services:
  db:
    mem_limit: 2048m
    image: mysql:8.0
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_DATABASE: "${MYSQL_DB}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - 3306:3306
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - wp-network
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - 8081:80
    env_file: .env
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - wp-network
  wp:
    depends_on:
      - db
    image: wordpress:6.6.1-apache
    restart: unless-stopped
    ports:
      - 8080:80
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: "${MYSQL_DB}"
      WORDPRESS_DB_USER: "${MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - ./wp-content:/var/www/html/wp-content
    networks:
      - wp-network

networks:
  wp-network:
    driver: bridge
